-- DELETED in FASE 4 — superseded by supabase/migrations/000_initial_schema.sql
-- which is now the single source of truth for the Hermes Gastro schema.
-- Run `git rm supabase/migrations/20260421_theme_config.sql` to remove from the repo.
